---
- name: Push to Registry and Deploy
  hosts: localhost
  vars:
    repo_name: "your-dockerhub-user/my-app"

  tasks:
    - name: Log into DockerHub
      community.docker.docker_login:
        username: "{{ docker_user }}"
        password: "{{ docker_pass }}"

    - name: Push image to DockerHub
      community.docker.docker_image:
        name: "{{ repo_name }}:{{ image_tag }}"
        push: yes
        source: local

    - name: Run the updated container
      community.docker.docker_container:
        name: my-active-app
        image: "{{ repo_name }}:{{ image_tag }}"
        state: started
        recreate: yes
        ports:
          - "80:80"