---
- name: Push to Registry and Deploy
  hosts: all  # Changed from localhost to 'all' to target your QA/Staging agents
  become: true
  vars:
    repo_name: "omergldb/hi-python"

  tasks:
    - name: Log into DockerHub
      community.docker.docker_login:
        username: "{{ docker_user }}"
        password: "{{ docker_password }}"

    - name: Pull latest image
      community.docker.docker_image:
        name: "{{ repo_name }}"
        source: pull

    - name: Run Docker container
      community.docker.docker_container:
        name: my-python-app
        image: "{{ repo_name }}"
        state: started
        restart_policy: always
        published_ports:
          - "80:5000"